---
- name: Create OpenStack VMs and auto-register to Rancher
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ###########################################################################
    # Rancher details
    ###########################################################################
    rancher_url: "https://10.68.0.173"
    rancher_token: "token-rqh8z:njslgl8dqqv6wp65dlm8ff9mq29ztghffxkqrvzbcst885r2sl2gnw"
    cluster_name: "{{ cluster_name }}"

    ###########################################################################
    # Survey variables (AAP)
    ###########################################################################
    vm_count: "{{ vm_count | int }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_security_groups: "{{ vm_security_groups }}"
    vm_names_list: "{{ vm_name_prefix.split(',') | map('trim') | list }}"

    ###########################################################################
    # Derived variables
    ###########################################################################
    parsed_security_groups: "{{ vm_security_groups.split(',') | map('trim') | list }}"

    ###########################################################################
    # VM details
    ###########################################################################
    vm_image: "0f92312d-bbcf-4c5a-964a-cfa4898940bd"
    vm_keypair: "k8"
    root_volume_size: 40   # 🔥 FIX: root disk size

    ###########################################################################
    # OpenStack auth
    ###########################################################################
    os_auth_url: "https://keystone-public-openstack.apps.pgrhoso.dccloud.com"
    os_project_name: "admin"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "stl@123"
    os_region_name: "regionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:
  ###########################################################################
  # VALIDATION
  ###########################################################################
  - name: Validate VM count and names
    assert:
      that:
        - vm_count >= 1
        - vm_names_list | length == vm_count
      fail_msg: "vm_count must match number of VM names"

  ###########################################################################
  # AUTO ROLE GENERATION (GUARANTEED ALL ROLES)
  ###########################################################################
  - name: Generate roles automatically
    set_fact:
      parsed_roles: >-
        {{
          ['etcd,controlplane,worker']
          if vm_count == 1
          else
          (
            range(0, vm_count)
            | map('mod', 3)
            | map('extract', {
                0: 'etcd',
                1: 'controlplane',
                2: 'worker'
              })
            | list
          )
        }}

  - name: Build VM to role mapping
    set_fact:
      vm_role_map: "{{ vm_names_list | zip(parsed_roles) | list }}"

  ###########################################################################
  # GET RANCHER CLUSTER INFO
  ###########################################################################
  - name: Get cluster ID from Rancher
    uri:
      url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: cluster_info

  - name: Fail if cluster not found
    fail:
      msg: "Cluster '{{ cluster_name }}' not found in Rancher"
    when: cluster_info.json.data | length == 0

  - name: Set cluster ID
    set_fact:
      cluster_id: "{{ cluster_info.json.data[0].id }}"

  ###########################################################################
  # GET RANCHER JOIN COMMAND
  ###########################################################################
  - name: Get registration token
    uri:
      url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: reg_info
    until:
      - reg_info.json.data | length > 0
      - reg_info.json.data[0].nodeCommand is defined
      - reg_info.json.data[0].nodeCommand != ""
    retries: 20
    delay: 5

  - name: Prepare node join command
    set_fact:
      node_command: "{{ reg_info.json.data[0].nodeCommand | replace('curl ', 'curl -k ') }}"

  ###########################################################################
  # CLOUD-INIT (FIXED – NO containerd INSTALL)
  ###########################################################################
  - name: Create cloud-init files
    copy:
      dest: "/tmp/cloud-init-{{ item.0 }}.yml"
      content: |
        #cloud-config
        package_update: true
        packages:
          - curl
          - jq
          - nfs-common

        runcmd:
          - swapoff -a
          - sed -i '/ swap / s/^/#/' /etc/fstab

          - modprobe overlay
          - modprobe br_netfilter

          - |
            cat <<EOF >/etc/sysctl.d/99-kubernetes.conf
            net.bridge.bridge-nf-call-iptables=1
            net.bridge.bridge-nf-call-ip6tables=1
            net.ipv4.ip_forward=1
            EOF
          - sysctl --system

          - sleep 60

          - |
            set -eux
            CMD="{{ node_command }}"
            {% if 'etcd' in item.1 %}CMD="$CMD --etcd"{% endif %}
            {% if 'controlplane' in item.1 %}CMD="$CMD --controlplane"{% endif %}
            {% if 'worker' in item.1 %}CMD="$CMD --worker"{% endif %}
            CMD="$CMD --node-name {{ item.0 }}"
            echo "$CMD" > /root/join.sh
            chmod +x /root/join.sh
            bash -x /root/join.sh
    loop: "{{ vm_role_map }}"

  ###########################################################################
  # CREATE VMs (BOOT FROM VOLUME FIX)
  ###########################################################################
  - name: Create VM on OpenStack (boot from volume)
    openstack.cloud.server:
      state: present
      name: "{{ item.0 }}"

      boot_from_volume: true
      volume_size: "{{ root_volume_size }}"
      delete_volume_on_termination: true
      image: "{{ vm_image }}"

      flavor: "{{ vm_flavor }}"
      key_name: "{{ vm_keypair }}"
      network: "{{ vm_net }}"
      security_groups: "{{ parsed_security_groups }}"
      userdata: "{{ lookup('file', '/tmp/cloud-init-' + item.0 + '.yml') }}"

      auto_ip: yes
      wait: yes
      timeout: 900
      validate_certs: false
    environment:
      OS_AUTH_URL: "{{ os_auth_url }}"
      OS_PROJECT_NAME: "{{ os_project_name }}"
      OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
      OS_USERNAME: "{{ os_username }}"
      OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
      OS_PASSWORD: "{{ os_password }}"
      OS_REGION_NAME: "{{ os_region_name }}"
      OS_INTERFACE: "{{ os_interface }}"
      OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
    loop: "{{ vm_role_map }}"

  ###########################################################################
  # WAIT FOR CLUSTER
  ###########################################################################
  - name: Wait for cluster to become active
    uri:
      url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: cluster_status
    until: cluster_status.json.state == "active"
    retries: 120
    delay: 10

  ###########################################################################
  # CLEANUP
  ###########################################################################
  - name: Clean temporary cloud-init files
    file:
      path: "/tmp/cloud-init-{{ item }}.yml"
      state: absent
    loop: "{{ vm_names_list }}"

  - name: Success message
    debug:
      msg: |
        ✅ SUCCESS!
        Cluster: {{ cluster_name }}
        State: {{ cluster_status.json.state }}
        VMs: {{ vm_names_list | join(', ') }}
